target 'Gogobit' do
    pod 'AFNetworking', '~> 2.0'
    pod 'AFNetworking+AutoRetry'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'YYCategories'
    pod 'YYWebImage'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TWMessageBarManager'
    pod 'CRToast', '~> 0.0.7'
    pod 'MYBlurIntroductionView'
    pod 'EAIntroView', '~> 2.9.0'
    pod 'SMPageControl', '~> 1.2'
end
